server:
  servlet:
    context-path: 
  port: ${PORT:9476}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ec2-34-199-149-157.compute-1.amazonaws.com:5432/da9fi2mtfce233}
    username: fltjpiyqcbnuwk
    password: 1d4502fe8d65d29719f03ecac52691e10a2321c2b69b6a6cfa1afb60677e5bf4
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: ${HIBERNATE_SHOW_SQL:false}
    properties:
      hibernate:
        generate_statistics: ${HIBERNATE_STATISTICS:false}
        temp:
          use_jdbc_metadata_defaults: false

oauth2-config:
  client-id: ${OAUTH2_CLIENT_ID:76179baad962d1b8ce4d}
  client-secret: ${OAUTH2_CLIENT_SECRET:8faedc0e6e1520d13f06f787d6760c303f3e8768}
  server-url: ${OAUTH2_SERVER_URL:https://development-oauth-server.herokuapp.com}

security:
  oauth2:
    client:
      clientId: ${oauth2-config.client-id}
      clientSecret: ${oauth2-config.client-secret}
      accessTokenUri: ${oauth2-config.server-url}/oauth/token
      userAuthorizationUri: ${oauth2-config.server-url}/oauth/authorize

    resource:
      userInfoUri: ${oauth2-config.server-url}/user/info
      tokenInfoUri: ${oauth2-config.server-url}/oauth/check_token
